### ISSUE TITLE
Master is hosed AGAIN!

### ISSUE THREAD

**Issue by aethelwulffe** [aethelwulffe/PQRS_Gateway#14]
Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\AlphaFiles\bidenis\PQRS_Gateway\qltkt0sr.5ks.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Gitpad.Program.Main(String[] args)
error: There was a problem with the editor 'gitpad'.
Please supply the message using either -m or -F option.
C:\AlphaFiles\bidenis\PQRS_Gateway [master +0 ~2372 -218 | +1 ~0 -0 !]> git revert -m1 HEAD
error: Your local changes would be overwritten by revert.
hint: Commit your changes or stash them to proceed.
fatal: revert failed
C:\AlphaFiles\bidenis\PQRS_Gateway [master +0 ~2372 -218 | +1 ~0 -0 !]> git revert -m1 HEAD
error: Your local changes would be overwritten by revert.
hint: Commit your changes or stash them to proceed.
fatal: revert failed
C:\AlphaFiles\bidenis\PQRS_Gateway [master +0 ~2372 -218 | +1 ~0 -0 !]>

So now I have no idea of how to revert that damn merge.

**Comment by aethelwulffe** [comment]
Did the following, still don't look right...

oemr501c3       https://github.com/oemr501c3/openemr.git (fetch)
oemr501c3       https://github.com/oemr501c3/openemr.git (push)
origin  https://github.com/aethelwulffe/PQRS_Gateway.git (fetch)
origin  https://github.com/aethelwulffe/PQRS_Gateway.git (push)
C:\AlphaFiles\bidenis\PQRS_Gateway [master]> git remote add upstream https://github.com/oemr501c3/openemr.git
C:\AlphaFiles\bidenis\PQRS_Gateway [master]> git remote -v
oemr501c3       https://github.com/oemr501c3/openemr.git (fetch)
oemr501c3       https://github.com/oemr501c3/openemr.git (push)
origin  https://github.com/aethelwulffe/PQRS_Gateway.git (fetch)
origin  https://github.com/aethelwulffe/PQRS_Gateway.git (push)
upstream        https://github.com/oemr501c3/openemr.git (fetch)
upstream        https://github.com/oemr501c3/openemr.git (push)
C:\AlphaFiles\bidenis\PQRS_Gateway [master]> git fetch upstream
From https://github.com/oemr501c3/openemr
 * [new branch]      5010       -> upstream/5010
 * [new branch]      master     -> upstream/master
 * [new branch]      mh_forms_openemr -> upstream/mh_forms_openemr
 * [new branch]      rel-410    -> upstream/rel-410
 * [new branch]      rel-411    -> upstream/rel-411
 * [new branch]      rel-412    -> upstream/rel-412
 * [new branch]      rel-420    -> upstream/rel-420
 * [new branch]      x12-5010   -> upstream/x12-5010
C:\AlphaFiles\bidenis\PQRS_Gateway [master]> git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
C:\AlphaFiles\bidenis\PQRS_Gateway [master]> git merge upstream/master
Already up-to-date.
C:\AlphaFiles\bidenis\PQRS_Gateway [master]>

**Comment by aethelwulffe** [comment]
git reset --hard upstream/master  
git push origin master --force 

That worked great!  Woohoo!  Seriously, Github should update their crappy tutorials.

**Comment by aethelwulffe** [comment]
Closing this issue, but it is a good one for reference.
